import "./global.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<header>Cabecera</header>
				<main>{children}</main>
				<footer> Este es el footer</footer>
			</body>
		</html>
	);
}
